# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8da281b027cb50c0669f3c8aed7a78bb"
name = "Reel Section"
application_url = "https://reel-section.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
scopes = "read_products,read_themes"

[auth]
redirect_urls = [
  "https://reel-section.onrender.com/auth/callback",
  "https://reel-section.onrender.com/auth/shopify/callback",
  "https://reel-section.onrender.com/api/auth/callback",
  "https://reel-section.onrender.com/app/pricing"
]

[app_proxy]
url = "https://reel-section.onrender.com/a/reelsection"
subpath = "reelsection"
prefix = "apps"
